WITH A AS(
    SELECT I.ANIMAL_ID, I.NAME, TIMESTAMPDIFF(SECOND, I.DATETIME, O.DATETIME) AS TD
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY TD DESC
)
SELECT ANIMAL_ID, NAME
FROM A
LIMIT 2;