WITH CH AS (
    SELECT C.CAR_ID, H.HISTORY_ID, C.DAILY_FEE, TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1 AS DF,
        CASE
            WHEN CAR_TYPE = '트럭' THEN
                        CASE
                            WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
                            WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
                            WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE)+1 >= 90 THEN '90일 이상'
                            ELSE '없음'
                        END
            END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭'
) 

SELECT C.HISTORY_ID, 
    FLOOR(CASE
            WHEN C.DURATION_TYPE != '없음' THEN C.DF*(C.DAILY_FEE*(0.01)*(100-P.DISCOUNT_RATE))
            ELSE C.DAILY_FEE * C.DF
          END) AS FEE
FROM CH C LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, C.HISTORY_ID DESC;