WITH A AS (
    SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_CNCL_YN, A.APNT_CNCL_YMD, A.APNT_YMD
    FROM PATIENT P JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
    WHERE A.APNT_YMD REGEXP '^2022-04-13' AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
)

SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM A
ORDER BY APNT_YMD